# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8E81eHl9YKgoaMEz58gzg4kSEblgnUE
"""

from flask import Flask, render_template, request
import pickle
import streamlit as st
import requests

def main():
    # front end elements of the web page
    html_temp = """
      <div style ="background-color:#410042; padding:24px; border-radius:10px;">
    <h1 style ="color:white;text-align:center;">Website Rekomendasi Aktivitas (Daily Activity)</h1>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-6 banner-info">
                <h2 class="judul">Rekomendasi kegiatan sehari-hari
                    yang dapat anda lakukan
                    di waktu luang</h2>
                <p></p>
                <p class="deskripsi">Ayo cari tau kegiatan apa yang dapat kita dilakukan...
                </p>
            </div>
            <div class="col-sm-6 banner-img" style="margin-left: 10rem;">
                <img src="https://blue.kumparan.com/image/upload/fl_progressive,fl_lossy,c_fill,q_auto:best,f_jpg,w_480/rehq64gy39fwdgxsyvvb.jpg"
                    style="height: 430px; border-radius:50px; " alt="mylist" class="img-jumbotron">
            </div>
        </div>
    </div>

   """

    st.markdown(html_temp, unsafe_allow_html = True)

if __name__=='__main__':
    main()


def activity_recommendations(Hobi):
    index = df[df['Hobi'] == Hobi].index[0]
    distances = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1])
    recommended_activity1 = []
    recommended_activity2 = []
    recommended_activity3 = []
    recommended_activity4 = []
    recommended_activity5 = []
    for i in distances[1:6]:
        Hobi = df.iloc[i[0]].Hobi
        recommended_activity1.append(df.iloc[i[0]].Hobi)

    return recommended_activity1, recommended_activity2, recommended_activity3, recommended_activity4, recommended_activity5


st.header('Activity Recommendation System')
df = pickle.load(open('activity.pkl','rb'))
similarity = pickle.load(open('similarity.pkl','rb'))


activity_list = df['Hobi'].values
selected_activity = st.selectbox(
    "Type or select your hobby from the dropdown",
    activity_list
)

if st.button('Show Recommendation'):
    recommended_activity1,recommended_activity2, recommended_activity3, recommended_activity4, recommended_activity5 = activity_recommendations(selected_activity)
    col1, col2, col3, col4, col5 = st.beta_columns(5)
    with col1:
        st.text(recommended_activity1[0])

def main() :
     html_temp = """
     <h1 class="activity-judul" style="color:#410042">About</h1>
    <hr class="garis-2">
    <div class="container about-card" style="text-align: center;">
        <div class="row">
            <div class="col-sm-6">
                <div class="card about h-100">
                    <img src="https://github.com/Reistha10/Capstone_Project018/raw/master/photo_2021-07-14_23-48-04.jpg"
                    style="height: 200px; width: 200px;"
                        alt="" class="card-img-top rounded-circle img-thumbnail mx-auto d-block">
                    <div class="card-body">
                        <p class="card-text">
                            Nama : Tiara Lailatul Nikmah <br>
                            Mahasiswa S1 Teknik Informatika <br>
                            Hobi Membaca<br>
                            Alamat Desa Trimulyo RT/RW:04/02, Juwana, Pati<br>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card about h-100">
                    <img src="https://github.com/Reistha10/Capstone_Project018/raw/master/photo_2021-12-22_20-53-37.jpg"
                        style="height: 200px; width: 200px; "alt="" class="card-img-top rounded-circle img-thumbnail mx-auto d-block">
                    <div class="card-body">
                        <p class="card-text">
                            <!-- <li>Nama : Reistha Ramadhanty</li>
                            <li>Mahasiswa S1 Teknik Informatika</li>
                            <li>Hobi Menggambar</li>
                            <li>Alamat Jl. Samratulangi No. 06/13, Bandar Lampung</li> -->
                            Nama : Reistha Ramadhanty <br>
                            Mahasiswa S1 Teknik Informatika <br>
                            Hobi Menggambar <br>
                            Alamat Jl. Samratulangi No. 06/13, Bandar Lampung <br>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container contact">
        <div class="card-body">
            <h1 class=" card-title contact-judul" style="color:#410042">Contact</h1>
             <hr class="garis-2">
            <p class="card-text contact-text">
            <ul style="color: white; background-color: #410042; text-align:center; padding:30px; border-radius:30px;">
                <p style="font-weight: bold;">Email : </p>
                <li style="color: white;">tiaralaila21@gmail.com
                </li>
                <li style="color: white;">reistharamadhanty10@gmail.com
                </li>
                <br>
                <p style="font-weight: bold;">Telepon : </p>
                <li style="color: white;">+6289635924667 (Tiara)</li>
                <li style="color: white;">+62895355431111 (Reistha)</li>
                <br>
                <p style="font-weight: bold;">DM Instagram : </p>
                <li style="color: white;">@tiara_laila</li>
                <li style="color: white;">@reistharamadhanty</li>
            </ul>
            </p>
        </div>
    </div>
     """
     st.markdown(html_temp, unsafe_allow_html = True)

if __name__=='__main__':
    main()
